# Generated by Django 3.2.7 on 2021-09-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
