# Generated by Django 3.2.7 on 2021-09-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
